name: hello-world-docker-action-latif


on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello World Latif
        uses: vedicsoftcts/hello-world-docker-action-latif@v1.0.1
        with:
          who-to-greet: 'Latif Hello World test'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
